// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjj00jRWVEqmff8FYucY0GZL5D-KXWa-w',
    appId: '1:1002687659302:web:161b87cba30e6e382955e7',
    messagingSenderId: '1002687659302',
    projectId: 'reserva-ya-aeebc',
    authDomain: 'reserva-ya-aeebc.firebaseapp.com',
    storageBucket: 'reserva-ya-aeebc.appspot.com',
    measurementId: 'G-0C1XJG0RLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCXAvIlqs38gRecrgTigsEtkchk9iZG8',
    appId: '1:1002687659302:android:dc9ad4b4dfdf925a2955e7',
    messagingSenderId: '1002687659302',
    projectId: 'reserva-ya-aeebc',
    storageBucket: 'reserva-ya-aeebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48p1FbnhxZb1mfDQXFEUcdQB0LEveDGo',
    appId: '1:1002687659302:ios:1bf09332e006fe622955e7',
    messagingSenderId: '1002687659302',
    projectId: 'reserva-ya-aeebc',
    storageBucket: 'reserva-ya-aeebc.appspot.com',
    iosClientId: '1002687659302-mmekvjjp1rnmtc6f85gsneqdhft8dibn.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyect',
  );
}
