// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0XY_dfLwvwnzHuqWD_flxPKTeleO4fI',
    appId: '1:875148103607:web:ca3e10adab6c6b99fc2232',
    messagingSenderId: '875148103607',
    projectId: 'reservayamovil',
    authDomain: 'reservayamovil.firebaseapp.com',
    storageBucket: 'reservayamovil.appspot.com',
    measurementId: 'G-CT4WFG4NZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo4m3SZwsyAnwNd3DmxJsd01v-L4adSw8',
    appId: '1:875148103607:android:de7b9cd5b731a5c8fc2232',
    messagingSenderId: '875148103607',
    projectId: 'reservayamovil',
    storageBucket: 'reservayamovil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwCiv4pzgV4iBofaj9y5ORR12Vlr-CVI',
    appId: '1:875148103607:ios:369b97b0cf079643fc2232',
    messagingSenderId: '875148103607',
    projectId: 'reservayamovil',
    storageBucket: 'reservayamovil.appspot.com',
    iosBundleId: 'com.example.proyect',
  );
}
