// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0kJ3LXe4OjliBSiEZHTREXUctmgjTA28',
    appId: '1:5895552841:web:ec0e1793c593fb4744e498',
    messagingSenderId: '5895552841',
    projectId: 'reservaya-aa832',
    authDomain: 'reservaya-aa832.firebaseapp.com',
    storageBucket: 'reservaya-aa832.appspot.com',
    measurementId: 'G-TH7XVT0Q1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTUoMB0Fwu1jYUHdZNV9TiQ9o1yvtP__w',
    appId: '1:5895552841:android:24d321c4bf8da00244e498',
    messagingSenderId: '5895552841',
    projectId: 'reservaya-aa832',
    storageBucket: 'reservaya-aa832.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0kJ3LXe4OjliBSiEZHTREXUctmgjTA28',
    appId: '1:5895552841:web:7dd712cee3b026fc44e498',
    messagingSenderId: '5895552841',
    projectId: 'reservaya-aa832',
    authDomain: 'reservaya-aa832.firebaseapp.com',
    storageBucket: 'reservaya-aa832.appspot.com',
    measurementId: 'G-TT73N845R0',
  );
}
